### DISCUSSION TITLE
Best way to host off a remote?

### DISCUSSION THREAD

**Discussion by hustlerone** [gollum/gollum#2107] [Q&A]
Hello. I have a remote repo. I would like Gollum to be able to pull from the remote and display.

Afaik it's not possible and you have to manually clone and stuff. What's the "reccomended" way of automatically having the local mirror update to match the remote?

**Comment by dometto** [comment]
This would depend a bit on the way you're hosting `gollum` (on a virtual machine, in a docker-compose or on kubernetes...) but I would generally say: why not just pull from the remote with a cronjob?

**Reply by hustlerone** [reply]
I host Gollum using Nix (NixOS).

I would probably get away with just doing a cronjob that pulls once a day but I wanted to know all the options available

**Reply by hustlerone** [reply]
Hey. I just found out that I could use webhooks to signal Gollum. However, I can't find the stupid tutorial again.

I can make it so on commit I send a packet to a webhook on loopback so gollum automatically pulls, but then how do I hook the damned thing?

**Reply by hustlerone** [reply]
And yes, while I could use a cronjob, it's going to be getting hacky really quickly on NixOS (not to mention that on startup i might get the journal filled with rubbish)

**Comment by Maddin-M** [comment]
I think just adding a cronjob is inefficient. I found a solution that I am quite happy with though:

I add the following to my config.rb (I am unfamiliar with Ruby so this piece is AI-generated):
```ruby
Precious::App.post("/pull-wiki-updates") do
  puts "Pulling Wiki updates..."
  Dir.chdir("/wiki") do
    system("git pull --ff-only")
  end
  status 200
end
```

This adds an endpoint, which then pulls the repo. There are ways to secure this better, like adding a secret in the header or having a lock while pulling, if lots of requests are coming in.
Then I have a Github (or in my case Forgejo) Actions workflow in my wiki repository:

```yaml
name: gollum-pull-wiki-updates

on:
  push:
    branches:
      - develop # or main or master
    paths-ignore:
      - '.forgejo/**'

jobs:
  gollum-pull-wiki-updates:
    if: github.actor != 'gollum' # if gollum itself pushed, it doesnt need to pull
    steps:
      - name: Call Gollum update endpoint
        run: |
          curl -X POST -H "Content-Length: 0" http://192.168.178.20/pull-wiki-updates
```

Which calls the previously created endpoint (my Gollum instance is on 192.168.178.20), if anyone other than my "gollum" user pushes a commit on the repo.

And also when a change is made in Gollum, it should be pushed (workflow is ignored when this happens):
```ruby
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
  puts "Triggered post commit..."
  credentials = Rugged::Credentials::UserPassword.new(username: "gollum", password: "my-cool-token")
  committer.wiki.repo.git.push("origin", committer.wiki.ref, credentials: credentials)
end
```

Hope this helps somebody!
