### ISSUE TITLE
Feature request: simplify layout customization

### ISSUE THREAD

**Issue by jstolarek** [gollum/gollum#1450]
I would like to customize my wiki layout in two ways:

1. Move sidebar from right to left
2. Widen the body of the page.

With Gollum 4.x I have found a relatively easy way to do it with `custom.css`. I moved the sidebar to the left with the following css:

```css
.has-rightbar #wiki-sidebar {
  float: left;
}

#wiki-body {
  float: right;
  clear: right;
}
```

and widened the page body with:

```css
.has-sidebar #wiki-body {
  width: 77%;
}

#wiki-wrapper {
    max-width: 90%;
}

#wiki-sidebar {
  width: 17%;
}
```

I just tested my wiki with the 5.x development branch and the above css is a recipe for a major disaster. After some experimenting it seems there is no simple way to perform the above customizations in an easy way. I am not complaining here about the lack of backward compatibility - this is understandable given a significant evolution from the 4.x branch. However, it is sad that there is no easy way to customize wiki appearance. Hence my feature request: **provide a way to easily customize basic layout settings like sidebar location, colours, text width, bullet-list styles, etc.** Perhaps allow custom mustache and scss files?

**Comment by bartkamphorst** [comment]
> provide a way to easily customize basic layout settings like sidebar location, colours, text width, bullet-list styles, etc. Perhaps allow custom mustache and scss files?

Both of these options are already supported. You can create your own mustache templates and point to them using `--template-dir [PATH]`. Custom CSS is supported precisely through `custom.css` and `--css`. 

I think your CSS example is simply pointing to HTML elements that have been renamed or restructured; I'll have a look to see if I can come up with a snippet that does what you want it to do.

**Comment by jstolarek** [comment]
> Both of these options are already supported.

Indeed, it is possible to point to a directory with custom mustache files, but I believe you cannot override just a single mustache file. You need to override all of them.

**Comment by bartkamphorst** [comment]
In 5.x, to change the sidebar from right to left, use the following in your `config.rb`.
```ruby
wiki_options = {sidebar: :left}
Precious::App.set(:wiki_options, wiki_options)
```
This functionality existed in 4.x but was broken in 5.x (see https://github.com/gollum/gollum/pull/1477) so you will have to `git pull` the latest changes on the 5.x branch.

As to your other request, most if not all the things you mentioned can be changed in `custom.css`. For example, here is a snippet to change the widths of the page and the sidebar, and the change the bullet list style to squares:

```css
.container-lg {
  max-width: 90%;
}

#sidebar-content {
  width: 17%;
}

ul {
  list-style-type: square;
}
```

Here's what that would look like:

![Screen Shot 2020-03-14 at 19 38 21](https://user-images.githubusercontent.com/571173/76688901-8f30eb80-6631-11ea-842b-bd3f71b6810f.png)
