### ISSUE TITLE
ACE editor breaks on non-ascii characters

### ISSUE THREAD

**Issue by vfrc2** [gollum/gollum#1880]
**Describe the bug**
ACE editor breaks on non-ascii characters. On input it misaligned rendered characters and cursor.
It may happens due to two different fonts used in ace editor:  
```css
#gollum-editor-body-ace {
    overflow: hidden;
    font-family: Consolas, "Liberation Mono", Courier, monospace;
    font-size: 1em;
    padding: 0;
}
...
.ace_editor {
    position: relative;
    overflow: hidden;
    font: 12px/normal 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;
    direction: ltr;
    text-align: left;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```

I fix this by providing custom css via `--css` option:
```css
#gollum-editor-body-ace {
    font-family: Monaco, Menlo, "Ubuntu Mono", Consolas, source-code-pro, monospace !important;
}
```

**To Reproduce**
1. Edit or create page
2. Start type 20+ non-asci characters

**Expected behavior**
Expect to input character renders on right positions

**Screenshots**

**Environment Info**
Run on official docker image.  

bash-5.1# gollum --versions
Gollum 5.3.0
Running on: aarch64-linux-musl with Ruby version 2.7.6
Using:
rugged 1.1.1
gollum-rugged_adapter 1.1.2
gollum-lib 5.1.3
Markdown rendering gem: kramdown
Other renderering gems:
RedCloth 4.3.2
org-ruby 0.9.12
creole 0.5.0
asciidoctor 2.0.17
wikicloth 0.8.3
