### ISSUE TITLE
GH Action Running Unprovoked

### ISSUE THREAD

**Issue by ArlinJae** [gollum/gollum#2082]
**Please read the [CONTRIBUTION GUIDELINES](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md) before submitting!**

If your have problems using or installing the software which stem from bugs in the software or a lack of documentation, we are always happy to help out! However, **for ordinary usage questions, please consider asking elsewhere**, for instance on [StackOverflow](http://stackoverflow.com/questions/tagged/gollum-wiki).

**Describe the bug**
I have a github action which I wish to be triggered when there's a change pushed to the repository's corresponding Github Wiki.

The action is responsible for automatically creating a table of contents on the Home.md page of the Wiki - this is done via the update_wiki.py function.

Here is my code - 
```yaml
name: Update Wiki Navigation

on:
  gollum:
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Checkout wiki repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Update wiki navigation
        run: |
          python .github/scripts/update_wiki.py
        env:
          WIKI_PATH: wiki/

      - name: Commit and push wiki changes
        run: |
          cd wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Home.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update navigation"
          git push
```

This action ran over over >2,000 times leading to me getting billed a decent amount. 
![Workflow runs · ArlinJaestartup_2024-December-01](https://github.com/user-attachments/assets/f21e6162-2907-425d-b9af-803a580bc377)

**To Reproduce**
1. Create a github action with the above code
2. Make a change on the github wiki, push that change
3. Watch as the action get triggered multiple times automatically

**Expected behavior**
It should be run a single time upon a change being made to the wiki.
