### ISSUE TITLE
Support notes

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#2112]
Github support the `[!NOTE]` tag to create a note like this:

> [!NOTE]
> A little note.

There are also other [alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts). Gitlab [also supports these](https://docs.gitlab.com/user/markdown/#alerts).

Gollum (at least with the default kramdown renderer) doesn't support this yet.

**Comment by Maddin-M** [comment]
While I wasn't able to apply the actual GitHub-style alerts/notes, I was able to hack something together to make it look as close as possible, with further options to customize it. I have this piece of code in my `config.rb`:

```ruby
GitHub::Markup::Markdown::MARKDOWN_GEMS['kramdown'] = proc { |content|
  html = Kramdown::Document.new(content).to_html

  html.gsub(/<blockquote>(.*?)<\/blockquote>/m) do |blockquote|
    inner = $1

    if inner =~ /\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]/
      type = $1.downcase
      label = case type
        when 'note' then 'Note'
        when 'tip' then 'Tip'
        when 'important' then 'Important'
        when 'warning' then 'Warning'
        when 'caution' then 'Caution'
      end

      inner.gsub!(/\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*/, '')
      paragraphs = inner.split(/<\/?p[^>]*>/).reject(&:empty?).map(&:strip)
      merged = "<p dir=\"auto\"><span class=\"github-alert-title\">#{label}<br></span>\n#{paragraphs.join("\n")}</p>"
      "<blockquote class=\"github-alert github-alert-#{type}\">#{merged}</blockquote>"
    else
      blockquote
    end
  end
}
```

Which basically looks for the notation style used by GitHub, converts it into a human-readable version (`[!NOTE]` becomes `Note`) and adds CSS classes for me to customize the looks with my `custom.css`. I know the icons are missing, but I was able to achieve this look in Gollum, and I think it's neat:

<img width="810" height="488" alt="Image" src="https://github.com/user-attachments/assets/852527ed-e206-448b-b8f2-6d6935b87bc5" />

(I did add a background to mine, because I think it looks better)

**Comment by ghst-0** [comment]
Here is a version that adds GitHub icons and background, I also included the custom.css.

<img alt="Image" src="https://github.com/user-attachments/assets/087d4cae-8ab8-4e1b-9700-e4cbc7122a46" />

**config.rb**
```ruby
# Add support for GitHub style alerts
GitHub::Markup::Markdown::MARKDOWN_GEMS['kramdown'] = proc { |content|
  html = Kramdown::Document.new(content).to_html

  html.gsub(/<blockquote>(.*?)<\/blockquote>/m) do |blockquote|
    inner = $1

    if inner =~ /\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]/
      type = $1.downcase
      label = case type
        when 'note' then 'Note'
        when 'tip' then 'Tip'
        when 'important' then 'Important'
        when 'warning' then 'Warning'
        when 'caution' then 'Caution'
      end
      icon = case type
        when 'note' then '<svg class="octicon octicon-info mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill="#0969da" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13ZM6.5 7.75A.75.75 0 0 1 7.25 7h1a.75.75 0 0 1 .75.75v2.75h.25a.75.75 0 0 1 0 1.5h-2a.75.75 0 0 1 0-1.5h.25v-2h-.25a.75.75 0 0 1-.75-.75ZM8 6a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg>'
        when 'tip' then '<svg class="octicon octicon-light-bulb mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill="#198032" d="M8 1.5c-2.363 0-4 1.69-4 3.75 0 .984.424 1.625.984 2.304l.214.253c.223.264.47.556.673.848.284.411.537.896.621 1.49a.75.75 0 0 1-1.484.211c-.04-.282-.163-.547-.37-.847a8.456 8.456 0 0 0-.542-.68c-.084-.1-.173-.205-.268-.32C3.201 7.75 2.5 6.766 2.5 5.25 2.5 2.31 4.863 0 8 0s5.5 2.31 5.5 5.25c0 1.516-.701 2.5-1.328 3.259-.095.115-.184.22-.268.319-.207.245-.383.453-.541.681-.208.3-.33.565-.37.847a.751.751 0 0 1-1.485-.212c.084-.593.337-1.078.621-1.489.203-.292.45-.584.673-.848.075-.088.147-.173.213-.253.561-.679.985-1.32.985-2.304 0-2.06-1.637-3.75-4-3.75ZM5.75 12h4.5a.75.75 0 0 1 0 1.5h-4.5a.75.75 0 0 1 0-1.5ZM6 15.25a.75.75 0 0 1 .75-.75h2.5a.75.75 0 0 1 0 1.5h-2.5a.75.75 0 0 1-.75-.75Z"></path></svg>'
        when 'important' then '<svg class="octicon octicon-report mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill="#8250df" d="M0 1.75C0 .784.784 0 1.75 0h12.5C15.216 0 16 .784 16 1.75v9.5A1.75 1.75 0 0 1 14.25 13H8.06l-2.573 2.573A1.458 1.458 0 0 1 3 14.543V13H1.75A1.75 1.75 0 0 1 0 11.25Zm1.75-.25a.25.25 0 0 0-.25.25v9.5c0 .138.112.25.25.25h2a.75.75 0 0 1 .75.75v2.19l2.72-2.72a.749.749 0 0 1 .53-.22h6.5a.25.25 0 0 0 .25-.25v-9.5a.25.25 0 0 0-.25-.25Zm7 2.25v2.5a.75.75 0 0 1-1.5 0v-2.5a.75.75 0 0 1 1.5 0ZM9 9a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"></path></svg>'
        when 'warning' then '<svg class="octicon octicon-alert mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill="#9a6700" d="M6.457 1.047c.659-1.234 2.427-1.234 3.086 0l6.082 11.378A1.75 1.75 0 0 1 14.082 15H1.918a1.75 1.75 0 0 1-1.543-2.575Zm1.763.707a.25.25 0 0 0-.44 0L1.698 13.132a.25.25 0 0 0 .22.368h12.164a.25.25 0 0 0 .22-.368Zm.53 3.996v2.5a.75.75 0 0 1-1.5 0v-2.5a.75.75 0 0 1 1.5 0ZM9 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"></path></svg>'
        when 'caution' then '<svg class="octicon octicon-stop mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill="#cf222e" d="M4.47.22A.749.749 0 0 1 5 0h6c.199 0 .389.079.53.22l4.25 4.25c.141.14.22.331.22.53v6a.749.749 0 0 1-.22.53l-4.25 4.25A.749.749 0 0 1 11 16H5a.749.749 0 0 1-.53-.22L.22 11.53A.749.749 0 0 1 0 11V5c0-.199.079-.389.22-.53Zm.84 1.28L1.5 5.31v5.38l3.81 3.81h5.38l3.81-3.81V5.31L10.69 1.5ZM8 4a.75.75 0 0 1 .75.75v3.5a.75.75 0 0 1-1.5 0v-3.5A.75.75 0 0 1 8 4Zm0 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg>'
      end
                             
      inner.gsub!(/\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*/, '')
      paragraphs = inner.split(/<\/?p[^>]*>/).reject(&:empty?).map(&:strip)
      merged = "<p dir=\"auto\"><span class=\"github-alert-title\">#{icon}#{label}<br></span>\n#{paragraphs.join("\n")}</p>"
      "<blockquote class=\"github-alert github-alert-#{type}\">#{merged}</blockquote>"
    else
      blockquote
    end
  end
}
```

**custom.css**
```css
/* GitHub style alerts */
.github-alert {
  padding: 8px 16px !important;
  margin-bottom: 16px !important;
  color: inherit !important;
  border-left: .25em solid #d1d9e0;
}

.github-alert-title {
  font-weight: bold;
  align-items: center;
  line-height: 1;
  display: flex;
}

.github-alert.github-alert-note {
  border-left-color: #0969da;
  background-color: #e2edfb;
}

.github-alert.github-alert-tip {
  border-left-color: #198032;
  background-color: #e1fbe1;
}

.github-alert.github-alert-important {
  border-left-color: #8250df;
  background-color: #f2edfb;
}

.github-alert.github-alert-warning {
  border-left-color: #9a6700;
  background-color: #f9f0de;
}

.github-alert.github-alert-caution {
  border-left-color: #cf222e;
  background-color: #f9dbdd;
}
```
