### ISSUE TITLE
Mount multiple Gollum-based Rack apps

### ISSUE THREAD

**Issue by mjrusso** [gollum/gollum#44]
Ideally I would like to be able do something like this in a `config.ru`:

```
require 'gollum/frontend/app'

run Rack::URLMap.new \
  "/wiki1" => Precious::App.new('path_to_repo_1'),
  "/wiki2" => Precious::App.new('path_to_repo_2')
```

Is something like this possible?  

I see that the latest code has `gollum_path` for setting the path of the repository, but it isn't obvious to me right now how to properly wire this up.

**Comment by craibuc** [comment]
Has there been any changes that would enable this feature?

**Comment by dometto** [comment]
I'm not sure what would prevent you from doing this tbh. Have you tried to get this working?

**Comment by craibuc** [comment]
I would, but I'm not sure that I understand the process.  Will you elaborate on it, please?

**Comment by dometto** [comment]
The documentation for mounting gollum as a rack app is [here](https://github.com/gollum/gollum/wiki/Using-Gollum-with-Rack). Mounting multiple apps is just a question of repeating that for different sub url's, as in @mjrusso's example in this thread.

**Comment by craibuc** [comment]
This *almost* works:

```ruby
#!/usr/bin/env ruby

require 'rubygems'
require 'gollum/app'
require 'rack'

# dummy application that returns env['HTTP_HOST'] and env['REQUEST_URI']
require 'HelloWorld'

builder = Rack::Builder.new do 
  map '/wiki/test0' do
    # run HelloWorld
    wiki_options = {:universal_toc => false}
    Precious::App.set(:gollum_path, './repo/test0')
    Precious::App.set(:default_markup, :markdown) # set your favorite markup language
    Precious::App.set(:wiki_options, wiki_options)
    run Precious::App
  end

  map '/wiki/test1' do
    # run HelloWorld
    wiki_options = {:universal_toc => false}
    Precious::App.set(:gollum_path, './repo/test1')
    Precious::App.set(:default_markup, :markdown) # set your favorite markup language
    Precious::App.set(:wiki_options, wiki_options)
    run Precious::App
  end
  
end

Rack::Server.start :app => builder
```
Unfortunately, both `/wiki/test0/` and `/wiki/test1` actually use the content of the `/repo/test1` repository.  If I enable a dummy application (HelloWorld) at `wiki/test1`, the `/wiki/wiki0` path to reference the correct repository (`/repo/test0`).

**Comment by pkuykendall** [comment]
I was able to get this to work by sub-classing `Precious::App`. I'm not sure if there are any considerations that I'm missing as to why this might be a bad idea (I'm sure there are, this was a quick hack), but it seems to work well for my uses. This works in Rails, I assume it would work in any Rack app, though.

```ruby
# config/routes.rb
require 'gollum/app'

class FirstWiki < Precious::App;
end
class SecondWiki < Precious::App;
end

Rails.application.routes.draw do
  wiki_options = {
      universal_toc: false,
      allow_editing: Rails.env.development?
  }
  FirstWiki.set(:gollum_path, Rails.root.join('wiki', 'First'))
  FirstWiki.set(:default_markup, :markdown) # set your favorite markup language
  FirstWiki.set(:wiki_options, wiki_options)
  mount FirstWiki, at: 'wiki/First'

  SecondWiki.set(:gollum_path, Rails.root.join('wiki', 'Second'))
  SecondWiki.set(:default_markup, :markdown) # set your favorite markup language
  SecondWiki.set(:wiki_options, wiki_options)
  mount SecondWiki, at: 'wiki/Second'
end

```

**Comment by guillaume-d** [comment]
@dometto said in https://github.com/gollum/gollum/issues/44#issuecomment-70109722:
> The documentation for mounting gollum as a rack app is [here](https://github.com/gollum/gollum/wiki/Using-Gollum-with-Rack). Mounting multiple apps is just a question of repeating that for different sub url's, as in @mjrusso's example in this thread.

Meanwhile the Rack page seems to have moved to [Gollum-via-Rack](https://github.com/gollum/gollum/wiki/Gollum-via-Rack).
It seems like the repeating advice above does not apply anymore as 
`run Precious::MapGollum.new(sub_dir)` now seems necessary.
Must one now define and use an own `MapGollum` class like for example in https://github.com/gollum/gollum/issues/1112#issuecomment-190750136, and then for each "mount-point" `run` a different (empty) class derived from `App::Precious` as @pkuykendall did for Rails???
Or is there a simpler way?

Sorry, Rails/Rack newbie here: any advice is very much appreciated!

BTW [Smeagol does not use Gollum anymore apparently](https://github.com/cloudogu/smeagol/blob/master/docs/architecture_en.md#wiki), so no help there.

**Comment by asano69** [comment]
**Working solution for gollum 6.1.0 (single process, multiple wikis)**

 After investigating the root cause, the problem is that gollum's internal code calls `Precious::App.gollum_path` and `Precious::App.wiki_options` directly (hardcoded to the parent class) rather than `settings.xxx`, which would resolve to the correct subclass. This makes the subclassing approach fail on write operations (`/gollum/create/*`, etc.).

 The workaround is to override those class methods on `Precious::App` to read from thread-local storage, and use a thin Rack middleware per wiki to inject the correct values before each request.

 Verified with `grep -r "Precious::App\." /usr/local/bundle/gems/gollum-6.1.0/lib/` — only two hardcoded calls exist: `Precious::App.gollum_path` (in `helpers.rb`) and `Precious::App.wiki_options` (in `helpers.rb`). The third hit, `Precious::App.settings.default_markup` in `create.rb`, is harmless since `Precious::App.settings` returns `Precious::App` itself.

 Full working setup: `config.ru` + `docker-compose.yml` below.

**config.ru:**
```ru
require 'gollum/app'

# Middleware that injects wiki-specific settings into thread-local storage
# before each request, since gollum hardcodes Precious::App.xxx calls internally.
class WikiContext
  def initialize(app, gollum_path:, wiki_options:)
    @app = app
    @gollum_path = gollum_path
    @wiki_options = wiki_options
  end

  def call(env)
    Thread.current[:gollum_path]  = @gollum_path
    Thread.current[:wiki_options] = @wiki_options
    @app.call(env)
  ensure
    Thread.current[:gollum_path]  = nil
    Thread.current[:wiki_options] = nil
  end
end

# Override class methods on Precious::App to read from thread-local storage
module Precious
  class App
    def self.gollum_path;  Thread.current[:gollum_path];  end
    def self.wiki_options; Thread.current[:wiki_options]; end
  end
end

Precious::App.set :default_markup, :markdown
Precious::App.set :host_authorization, {
  permitted_hosts: ENV.fetch('GOLLUM_HOSTS', '').split(',').map(&:strip)
}

# Parse GOLLUM_WIKIS: "name1:/path/to/repo1,name2:/path/to/repo2"
wikis = ENV.fetch('GOLLUM_WIKIS', '').split(',').map do |entry|
  name, path = entry.strip.split(':', 2)
  [name, path]
end

run Rack::URLMap.new(
  wikis.to_h do |name, path|
    wiki_options = { universal_toc: false, base_path: "/#{name}" }
    ["/#{name}", WikiContext.new(Precious::App, gollum_path: path, wiki_options: wiki_options)]
  end
)

```

**compose.yaml:**
```yaml
services:
  gollum:
    image: ghcr.io/gollum/gollum:sha-01a3610
    container_name: gollum
    entrypoint:
      - /bin/bash
      - -c
      - |
        for wiki in $$(echo "$$GOLLUM_WIKIS" | tr ',' '\n'); do
          path="$${wiki#*:}"
          mkdir -p "$$path"
          git -C "$$path" init 2>/dev/null || true
          git -C "$$path" config user.name "$${GOLLUM_AUTHOR_USERNAME:-Gollum}"
          git -C "$$path" config user.email "$${GOLLUM_AUTHOR_EMAIL:-gollum@localhost}"
        done
        exec rackup /app/config.ru -p 4567 --host 0.0.0.0
    expose:
      - 4567
    volumes:
      - ./config.ru:/app/config.ru:ro
      - ./first:/wiki/first
      - ./second:/wiki/second
    environment:
      - GOLLUM_HOSTS=gollum.app.internal
      - GOLLUM_WIKIS=first:/wiki/first,second:/wiki/second
      - GOLLUM_AUTHOR_USERNAME=Gollum
      - GOLLUM_AUTHOR_EMAIL=gollum@localhost
      - GIT_CONFIG_COUNT=1
      - GIT_CONFIG_KEY_0=safe.directory
      - GIT_CONFIG_VALUE_0=/wiki # covers /wiki/first and /wiki/seco
    restart: unless-stopped
    networks:
      - traefik_br
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gollum.rule=Host(`gollum.app.internal`)"
      - "traefik.http.routers.gollum.middlewares=tinyauth-in" # optional
      - "traefik.http.services.gollum.loadbalancer.server.port=4567"
networks:
  traefik_br:
    external: true
```
