### ISSUE TITLE
Table cells are always aligned left regardless of user specified alignment

### ISSUE THREAD

**Issue by david-macmahon** [gollum/gollum#700]
In gollum 2.4.13, text alignment in tables is always left (at least in Safari 5.1.9), regardless of any alignment the user may have specified.  I think it is due to line 243 (in gollum 2.4.13) of lib/gollum/public/gollum/css/template.css:

``` css
.markdown-body table tr th,
.markdown-body table tr td {
  border: 1px solid #ccc;
  text-align: left; /* <------ this is the suspect line */
  margin: 0;
  padding: 6px 13px;
}
```

Removing the suspect line fixes the table alignment issue for me using gollum 2.4.13 with Safari 5.1.9.
